name     = "hugo-pure"
license  = "MIT"
homepage = "https://github.com/undus5/hugo-pure"
demosite = "https://hugo-pure.undus.net"
tags     = ["Blog", "Minimal", "Responsive", "Light", "Dark", "Multilingual"]

[author]
name = "Undus"
homepage = "https://undus.net"

[module]
[module.hugoVersion]
extended = false
min      = "0.147.3"
